package com.snail.pojo.domain;

import java.util.Date;

public class ShareInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_info.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_info.share_icon
     *
     * @mbggenerated
     */
    private String shareIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_info.content_id
     *
     * @mbggenerated
     */
    private Integer contentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_info.share_url
     *
     * @mbggenerated
     */
    private String shareUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_info.share_desc
     *
     * @mbggenerated
     */
    private String shareDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_info.tag_id
     *
     * @mbggenerated
     */
    private Integer tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_info.tag_name
     *
     * @mbggenerated
     */
    private String tagName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_info.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_info.user_icon
     *
     * @mbggenerated
     */
    private String userIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_info.login_name
     *
     * @mbggenerated
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_info.scan_count
     *
     * @mbggenerated
     */
    private Integer scanCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_info.collect_count
     *
     * @mbggenerated
     */
    private Integer collectCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_info.comment_count
     *
     * @mbggenerated
     */
    private Integer commentCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_info.star_count
     *
     * @mbggenerated
     */
    private Integer starCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_info.create_at
     *
     * @mbggenerated
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_info.update_at
     *
     * @mbggenerated
     */
    private Date updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_info
     *
     * @mbggenerated
     */
    public ShareInfo(Integer id, String title, String shareIcon, Integer contentId, String shareUrl, String shareDesc, Integer tagId, String tagName, Integer userId, String userIcon, String loginName, Integer scanCount, Integer collectCount, Integer commentCount, Integer starCount, Date createAt, Date updateAt) {
        this.id = id;
        this.title = title;
        this.shareIcon = shareIcon;
        this.contentId = contentId;
        this.shareUrl = shareUrl;
        this.shareDesc = shareDesc;
        this.tagId = tagId;
        this.tagName = tagName;
        this.userId = userId;
        this.userIcon = userIcon;
        this.loginName = loginName;
        this.scanCount = scanCount;
        this.collectCount = collectCount;
        this.commentCount = commentCount;
        this.starCount = starCount;
        this.createAt = createAt;
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_info
     *
     * @mbggenerated
     */
    public ShareInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_info.id
     *
     * @return the value of share_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_info.id
     *
     * @param id the value for share_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_info.title
     *
     * @return the value of share_info.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_info.title
     *
     * @param title the value for share_info.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_info.share_icon
     *
     * @return the value of share_info.share_icon
     *
     * @mbggenerated
     */
    public String getShareIcon() {
        return shareIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_info.share_icon
     *
     * @param shareIcon the value for share_info.share_icon
     *
     * @mbggenerated
     */
    public void setShareIcon(String shareIcon) {
        this.shareIcon = shareIcon == null ? null : shareIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_info.content_id
     *
     * @return the value of share_info.content_id
     *
     * @mbggenerated
     */
    public Integer getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_info.content_id
     *
     * @param contentId the value for share_info.content_id
     *
     * @mbggenerated
     */
    public void setContentId(Integer contentId) {
        this.contentId = contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_info.share_url
     *
     * @return the value of share_info.share_url
     *
     * @mbggenerated
     */
    public String getShareUrl() {
        return shareUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_info.share_url
     *
     * @param shareUrl the value for share_info.share_url
     *
     * @mbggenerated
     */
    public void setShareUrl(String shareUrl) {
        this.shareUrl = shareUrl == null ? null : shareUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_info.share_desc
     *
     * @return the value of share_info.share_desc
     *
     * @mbggenerated
     */
    public String getShareDesc() {
        return shareDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_info.share_desc
     *
     * @param shareDesc the value for share_info.share_desc
     *
     * @mbggenerated
     */
    public void setShareDesc(String shareDesc) {
        this.shareDesc = shareDesc == null ? null : shareDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_info.tag_id
     *
     * @return the value of share_info.tag_id
     *
     * @mbggenerated
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_info.tag_id
     *
     * @param tagId the value for share_info.tag_id
     *
     * @mbggenerated
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_info.tag_name
     *
     * @return the value of share_info.tag_name
     *
     * @mbggenerated
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_info.tag_name
     *
     * @param tagName the value for share_info.tag_name
     *
     * @mbggenerated
     */
    public void setTagName(String tagName) {
        this.tagName = tagName == null ? null : tagName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_info.user_id
     *
     * @return the value of share_info.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_info.user_id
     *
     * @param userId the value for share_info.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_info.user_icon
     *
     * @return the value of share_info.user_icon
     *
     * @mbggenerated
     */
    public String getUserIcon() {
        return userIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_info.user_icon
     *
     * @param userIcon the value for share_info.user_icon
     *
     * @mbggenerated
     */
    public void setUserIcon(String userIcon) {
        this.userIcon = userIcon == null ? null : userIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_info.login_name
     *
     * @return the value of share_info.login_name
     *
     * @mbggenerated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_info.login_name
     *
     * @param loginName the value for share_info.login_name
     *
     * @mbggenerated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_info.scan_count
     *
     * @return the value of share_info.scan_count
     *
     * @mbggenerated
     */
    public Integer getScanCount() {
        return scanCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_info.scan_count
     *
     * @param scanCount the value for share_info.scan_count
     *
     * @mbggenerated
     */
    public void setScanCount(Integer scanCount) {
        this.scanCount = scanCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_info.collect_count
     *
     * @return the value of share_info.collect_count
     *
     * @mbggenerated
     */
    public Integer getCollectCount() {
        return collectCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_info.collect_count
     *
     * @param collectCount the value for share_info.collect_count
     *
     * @mbggenerated
     */
    public void setCollectCount(Integer collectCount) {
        this.collectCount = collectCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_info.comment_count
     *
     * @return the value of share_info.comment_count
     *
     * @mbggenerated
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_info.comment_count
     *
     * @param commentCount the value for share_info.comment_count
     *
     * @mbggenerated
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_info.star_count
     *
     * @return the value of share_info.star_count
     *
     * @mbggenerated
     */
    public Integer getStarCount() {
        return starCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_info.star_count
     *
     * @param starCount the value for share_info.star_count
     *
     * @mbggenerated
     */
    public void setStarCount(Integer starCount) {
        this.starCount = starCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_info.create_at
     *
     * @return the value of share_info.create_at
     *
     * @mbggenerated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_info.create_at
     *
     * @param createAt the value for share_info.create_at
     *
     * @mbggenerated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_info.update_at
     *
     * @return the value of share_info.update_at
     *
     * @mbggenerated
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_info.update_at
     *
     * @param updateAt the value for share_info.update_at
     *
     * @mbggenerated
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
}