package com.snail.pojo.domain;

import java.util.Date;

public class ShareTag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_tag.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_tag.tag_name
     *
     * @mbggenerated
     */
    private String tagName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_tag.tag_type
     *
     * @mbggenerated
     */
    private String tagType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_tag.creat_at
     *
     * @mbggenerated
     */
    private Date creatAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_tag.update_at
     *
     * @mbggenerated
     */
    private Date updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_tag
     *
     * @mbggenerated
     */
    public ShareTag(Integer id, String tagName, String tagType, Date creatAt, Date updateAt) {
        this.id = id;
        this.tagName = tagName;
        this.tagType = tagType;
        this.creatAt = creatAt;
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_tag
     *
     * @mbggenerated
     */
    public ShareTag() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_tag.id
     *
     * @return the value of share_tag.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_tag.id
     *
     * @param id the value for share_tag.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_tag.tag_name
     *
     * @return the value of share_tag.tag_name
     *
     * @mbggenerated
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_tag.tag_name
     *
     * @param tagName the value for share_tag.tag_name
     *
     * @mbggenerated
     */
    public void setTagName(String tagName) {
        this.tagName = tagName == null ? null : tagName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_tag.tag_type
     *
     * @return the value of share_tag.tag_type
     *
     * @mbggenerated
     */
    public String getTagType() {
        return tagType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_tag.tag_type
     *
     * @param tagType the value for share_tag.tag_type
     *
     * @mbggenerated
     */
    public void setTagType(String tagType) {
        this.tagType = tagType == null ? null : tagType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_tag.creat_at
     *
     * @return the value of share_tag.creat_at
     *
     * @mbggenerated
     */
    public Date getCreatAt() {
        return creatAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_tag.creat_at
     *
     * @param creatAt the value for share_tag.creat_at
     *
     * @mbggenerated
     */
    public void setCreatAt(Date creatAt) {
        this.creatAt = creatAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_tag.update_at
     *
     * @return the value of share_tag.update_at
     *
     * @mbggenerated
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_tag.update_at
     *
     * @param updateAt the value for share_tag.update_at
     *
     * @mbggenerated
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
}