package com.snail.pojo.domain;

import java.util.Date;

public class ShareUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_user.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_user.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_user.share_id
     *
     * @mbggenerated
     */
    private Integer shareId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_user.option_type
     *
     * @mbggenerated
     */
    private String optionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_user.comment
     *
     * @mbggenerated
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_user.creat_at
     *
     * @mbggenerated
     */
    private Date creatAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_user.update_at
     *
     * @mbggenerated
     */
    private Date updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user
     *
     * @mbggenerated
     */
    public ShareUser(Integer id, Integer userId, Integer shareId, String optionType, String comment, Date creatAt, Date updateAt) {
        this.id = id;
        this.userId = userId;
        this.shareId = shareId;
        this.optionType = optionType;
        this.comment = comment;
        this.creatAt = creatAt;
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user
     *
     * @mbggenerated
     */
    public ShareUser() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_user.id
     *
     * @return the value of share_user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_user.id
     *
     * @param id the value for share_user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_user.user_id
     *
     * @return the value of share_user.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_user.user_id
     *
     * @param userId the value for share_user.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_user.share_id
     *
     * @return the value of share_user.share_id
     *
     * @mbggenerated
     */
    public Integer getShareId() {
        return shareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_user.share_id
     *
     * @param shareId the value for share_user.share_id
     *
     * @mbggenerated
     */
    public void setShareId(Integer shareId) {
        this.shareId = shareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_user.option_type
     *
     * @return the value of share_user.option_type
     *
     * @mbggenerated
     */
    public String getOptionType() {
        return optionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_user.option_type
     *
     * @param optionType the value for share_user.option_type
     *
     * @mbggenerated
     */
    public void setOptionType(String optionType) {
        this.optionType = optionType == null ? null : optionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_user.comment
     *
     * @return the value of share_user.comment
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_user.comment
     *
     * @param comment the value for share_user.comment
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_user.creat_at
     *
     * @return the value of share_user.creat_at
     *
     * @mbggenerated
     */
    public Date getCreatAt() {
        return creatAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_user.creat_at
     *
     * @param creatAt the value for share_user.creat_at
     *
     * @mbggenerated
     */
    public void setCreatAt(Date creatAt) {
        this.creatAt = creatAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_user.update_at
     *
     * @return the value of share_user.update_at
     *
     * @mbggenerated
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_user.update_at
     *
     * @param updateAt the value for share_user.update_at
     *
     * @mbggenerated
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
}