package com.snail.dao;

import com.snail.pojo.domain.ShareTag;
import com.snail.pojo.domain.ShareTagExample;
import java.util.List;

import com.snail.pojo.vo.ShareTagVo;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface ShareTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_tag
     *
     * @mbggenerated
     */
    int countByExample(ShareTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_tag
     *
     * @mbggenerated
     */
    int deleteByExample(ShareTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_tag
     *
     * @mbggenerated
     */
    @Insert({
        "insert into `share_tag` (`id`, `tag_name`, ",
        "`category_id`, `creat_at`, ",
        "`update_at`)",
        "values (#{id,jdbcType=INTEGER}, #{tagName,jdbcType=VARCHAR}, ",
        "#{categoryId,jdbcType=INTEGER}, #{creatAt,jdbcType=TIMESTAMP}, ",
        "#{updateAt,jdbcType=TIMESTAMP})"
    })
    int insert(ShareTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_tag
     *
     * @mbggenerated
     */
    int insertSelective(ShareTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_tag
     *
     * @mbggenerated
     */
    List<ShareTag> selectByExample(ShareTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_tag
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ShareTag record, @Param("example") ShareTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_tag
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ShareTag record, @Param("example") ShareTagExample example);

    /**
     * 查询标签列表
     *
     * @return 标签列表
     */
    List<ShareTagVo> selectAll();
}