package com.snail.dao;

import com.snail.pojo.domain.ShareCategory;
import com.snail.pojo.domain.ShareCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ShareCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_category
     *
     * @mbggenerated
     */
    int countByExample(ShareCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_category
     *
     * @mbggenerated
     */
    int deleteByExample(ShareCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_category
     *
     * @mbggenerated
     */
    @Delete({
        "delete from `share_category`",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_category
     *
     * @mbggenerated
     */
    @Insert({
        "insert into `share_category` (`id`, `category_name`, ",
        "`create_at`, `update`)",
        "values (#{id,jdbcType=INTEGER}, #{categoryName,jdbcType=VARCHAR}, ",
        "#{createAt,jdbcType=TIMESTAMP}, #{update,jdbcType=TIMESTAMP})"
    })
    int insert(ShareCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_category
     *
     * @mbggenerated
     */
    int insertSelective(ShareCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_category
     *
     * @mbggenerated
     */
    List<ShareCategory> selectByExample(ShareCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_category
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "`id`, `category_name`, `create_at`, `update`",
        "from `share_category`",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    ShareCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_category
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ShareCategory record, @Param("example") ShareCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_category
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ShareCategory record, @Param("example") ShareCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ShareCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_category
     *
     * @mbggenerated
     */
    @Update({
        "update `share_category`",
        "set `category_name` = #{categoryName,jdbcType=VARCHAR},",
          "`create_at` = #{createAt,jdbcType=TIMESTAMP},",
          "`update` = #{update,jdbcType=TIMESTAMP}",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ShareCategory record);
}