package com.snail.dao;

import com.snail.pojo.domain.ShareInfo;
import com.snail.pojo.domain.ShareInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ShareInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_info
     *
     * @mbggenerated
     */
    int countByExample(ShareInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_info
     *
     * @mbggenerated
     */
    int deleteByExample(ShareInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_info
     *
     * @mbggenerated
     */
    @Delete({
        "delete from `share_info`",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_info
     *
     * @mbggenerated
     */
    @Insert({
        "insert into `share_info` (`id`, `title`, ",
        "`share_icon`, `content_id`, ",
        "`share_url`, `share_desc`, ",
        "`tag_id`, `tag_name`, ",
        "`user_id`, `user_icon`, ",
        "`login_name`, `scan_count`, ",
        "`collect_count`, `comment_count`, ",
        "`star_count`, `create_at`, ",
        "`update_at`)",
        "values (#{id,jdbcType=INTEGER}, #{title,jdbcType=VARCHAR}, ",
        "#{shareIcon,jdbcType=VARCHAR}, #{contentId,jdbcType=INTEGER}, ",
        "#{shareUrl,jdbcType=VARCHAR}, #{shareDesc,jdbcType=VARCHAR}, ",
        "#{tagId,jdbcType=INTEGER}, #{tagName,jdbcType=VARCHAR}, ",
        "#{userId,jdbcType=INTEGER}, #{userIcon,jdbcType=VARCHAR}, ",
        "#{loginName,jdbcType=VARCHAR}, #{scanCount,jdbcType=INTEGER}, ",
        "#{collectCount,jdbcType=INTEGER}, #{commentCount,jdbcType=INTEGER}, ",
        "#{starCount,jdbcType=INTEGER}, #{createAt,jdbcType=TIMESTAMP}, ",
        "#{updateAt,jdbcType=TIMESTAMP})"
    })
    int insert(ShareInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_info
     *
     * @mbggenerated
     */
    int insertSelective(ShareInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_info
     *
     * @mbggenerated
     */
    List<ShareInfo> selectByExample(ShareInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_info
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "`id`, `title`, `share_icon`, `content_id`, `share_url`, `share_desc`, `tag_id`, ",
        "`tag_name`, `user_id`, `user_icon`, `login_name`, `scan_count`, `collect_count`, ",
        "`comment_count`, `star_count`, `create_at`, `update_at`",
        "from `share_info`",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    ShareInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ShareInfo record, @Param("example") ShareInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ShareInfo record, @Param("example") ShareInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ShareInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_info
     *
     * @mbggenerated
     */
    @Update({
        "update `share_info`",
        "set `title` = #{title,jdbcType=VARCHAR},",
          "`share_icon` = #{shareIcon,jdbcType=VARCHAR},",
          "`content_id` = #{contentId,jdbcType=INTEGER},",
          "`share_url` = #{shareUrl,jdbcType=VARCHAR},",
          "`share_desc` = #{shareDesc,jdbcType=VARCHAR},",
          "`tag_id` = #{tagId,jdbcType=INTEGER},",
          "`tag_name` = #{tagName,jdbcType=VARCHAR},",
          "`user_id` = #{userId,jdbcType=INTEGER},",
          "`user_icon` = #{userIcon,jdbcType=VARCHAR},",
          "`login_name` = #{loginName,jdbcType=VARCHAR},",
          "`scan_count` = #{scanCount,jdbcType=INTEGER},",
          "`collect_count` = #{collectCount,jdbcType=INTEGER},",
          "`comment_count` = #{commentCount,jdbcType=INTEGER},",
          "`star_count` = #{starCount,jdbcType=INTEGER},",
          "`create_at` = #{createAt,jdbcType=TIMESTAMP},",
          "`update_at` = #{updateAt,jdbcType=TIMESTAMP}",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ShareInfo record);
}