package com.snail.dao;

import com.snail.pojo.domain.ShareTag;
import com.snail.pojo.domain.ShareTagExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface ShareTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_tag
     *
     * @mbggenerated
     */
    int countByExample(ShareTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_tag
     *
     * @mbggenerated
     */
    int deleteByExample(ShareTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_tag
     *
     * @mbggenerated
     */
    @Insert({
        "insert into `share_tag` (`id`, `tag_name`, ",
        "`tag_type`, `creat_at`, ",
        "`update_at`)",
        "values (#{id,jdbcType=INTEGER}, #{tagName,jdbcType=VARCHAR}, ",
        "#{tagType,jdbcType=VARCHAR}, #{creatAt,jdbcType=TIMESTAMP}, ",
        "#{updateAt,jdbcType=TIMESTAMP})"
    })
    int insert(ShareTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_tag
     *
     * @mbggenerated
     */
    int insertSelective(ShareTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_tag
     *
     * @mbggenerated
     */
    List<ShareTag> selectByExample(ShareTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_tag
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ShareTag record, @Param("example") ShareTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_tag
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ShareTag record, @Param("example") ShareTagExample example);
}